version: 2
updates:
  # Configuration for Maven dependencies
  - package-ecosystem: "maven"
    directory: "/" # Location of your dependency manifests
    schedule:
      interval: "daily" # Check for updates daily

  # Configuration for npm dependencies
  - package-ecosystem: "npm"
    directory: "/" # Location of your dependency manifests
    schedule:
      interval: "daily" # Check for updates daily

  # Configuration for Python dependencies
  - package-ecosystem: "pip"
    directory: "/" # Location of your dependency manifests
    schedule:
      interval: "daily" # Check for updates daily
